include:
  - board: nice_nano_v2
    shield: sweep_central_dongle dongle_display
  - board: nice_nano_v2
    shield: sweep_central_left
  - board: nice_nano_v2
    shield: sweep_peripheral_left
  - board: nice_nano_v2
    shield: sweep_peripheral_right
  - board: nice_nano_v2
    shield: settings_reset
